/*
* Copyright (C) 2026 Romain Graillot
 *
 * This file is part of bbloc.
 *
 * bbloc is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * bbloc is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */
#ifndef HIGH_LIGHTER_H
#define HIGH_LIGHTER_H

#include <functional>
#include <optional>
#include <unordered_map>
#include <string_view>

#include <tree_sitter/api.h>

#include "../base/AutoCompleteCallback.h"
#include "../cursor/buffer/BufferEdit.h"
#include "../cursor/Cursor.h"
#include "HighLightId.h"
#include "Parser.h"
#include "TokenId.h"


/**
 * @brief Syntax highlighter using Tree-sitter for structured code parsing.
 *
 * Manages language-specific parsers, applies syntax highlighting, and supports
 * dynamic language switching based on file extensions or user commands.
 */
class HighLighter final {
private:
    /** Number of lines covered by the highlight cache window. */
    static constexpr uint32_t CACHE_LINE_COUNT = 512;

private:
    /** Reference to the cursor giving the text data to this highlighter */
    const Cursor &m_cursor;

    /** Compiled parsers indexed by highlighting mode; each Parser owns its tree-sitter query. */
    const std::unordered_map<HighLightId, Parser> m_parsers;

    /** The current active parser module, or nullptr. Is used only to avoid a map lookup for each character.  */
    const Parser *p_current_parser;

    /** The Tree-sitter parser instance. */
    TSParser *p_ts_parser;

    /** The syntax tree generated by parsing. */
    TSTree *p_ts_tree;

    /** Tree-sitter query cursor. */
    TSQueryCursor *p_ts_query_cursor;

    /** Painted TokenId per column for a window of lines starting at m_cache_start_line; TokenId::None means unpainted. */
    mutable std::vector<std::vector<TokenId>> m_line_cache;

    /** First line covered by m_line_cache. */
    mutable uint32_t m_cache_start_line;

    /** Tree-sitter input wrapper for reading source text. */
    TSInput m_input;

    /** Currently active highlighting mode. */
    HighLightId m_high_light;

    /** true when the tree-sitter tree must be reparsed. */
    bool m_is_dirty;

    /** true when an edit since the last parse changed the buffer line count. */
    bool m_edit_lines_shifted;

    /** First line touched by the edits accumulated since the last parse. */
    uint32_t m_dirty_line_min;

    /** Last line touched by the edits accumulated since the last parse. */
    uint32_t m_dirty_line_max;

private:
    /** @brief Tree-sitter input callback used to supply source code to the parser. */
    static const char *inputCallback(void *payload, uint32_t byteIndex, TSPoint position, uint32_t *bytesRead);

    /**
     * @brief Used by static inputCallback to read text from the cursor.
     *
     * @param line The line to start read.
     * @param column The column to start read.
     * @return A string view containing the line of text, starting from the said column, until the end of the said line (\n).
     */
    [[nodiscard]] std::optional<std::u16string_view> readCallback(uint32_t line, uint32_t column) const;

    /**
     * @brief Rebuilds the highlight cache for a window of lines centered on the given line.
     *
     * @param line The line that must be covered by the new cache window.
     */
    void updateCache(uint32_t line) const;

    /**
     * @brief Runs the highlight query and paints the cached rows within the given line range.
     *
     * Rows with an empty cell vector are lazily resized to their line's current length before painting.
     *
     * @param rootNode Root node of the syntax tree to query.
     * @param firstLine First line to paint (inclusive).
     * @param lastLine Last line to paint (inclusive).
     */
    void paintCacheLines(TSNode rootNode, uint32_t firstLine, uint32_t lastLine) const;

    /**
     * @brief Repaints the cached lines invalidated since the last parse.
     *
     * Covers the accumulated edit span unioned with the structural changes between the old and new
     * trees, clipped to the cached window. Must be called while p_ts_tree still holds the old tree.
     *
     * @param newTree The syntax tree produced by the latest parse.
     */
    void repaintChangedLines(TSTree *newTree);

public:
    /** @brief Deleted copy constructor. */
    HighLighter(const HighLighter &) = delete;

    /** @brief Deleted copy assignment operator. */
    HighLighter &operator=(const HighLighter &) = delete;

    /** @brief Free allocated resources. */
    ~HighLighter();

    /**
     * @brief Constructs the HighLighter with default values.
     *
     * @param cursor Reference to the source Cursor that feed data to this highlighter.
     */
    explicit HighLighter(Cursor &cursor);

    /**
     * @brief Sets the current syntax highlighting mode explicitly.
     *
     * @param highLight Highlight mode to activate.
     */
    void setMode(HighLightId highLight);

    /**
     * @brief Sets the highlighting mode based on file extension.
     *
     * This will fall back to no highlight if nothing matches.
     *
     * @param extension File extension (including the dot), e.g. ".cpp".
     */
    void setMode(std::string_view extension);

    /** @brief Parses or reparses the current input buffer. */
    void parse();

    /**
     * @brief Notifies the HighLighter about a range of text edits.
     *
     * @param edit Object describing the modified byte and position ranges. (provided by the Cursor class)
     */
    void edit(const BufferEdit &edit);

    /**
     * @brief Retrieves the TokenId (syntax classification) at a specific position.
     *
     * @param line Line number (zero-based).
     * @param column Column number (zero-based).
     * @return TokenId describing the syntax element at that position.
     */
    [[nodiscard]] TokenId getHighLightAtPosition(uint32_t line, uint32_t column) const;

    /** @return The current highlight mode name (e.g., "cpp", "json"). */
    [[nodiscard]] std::string_view getModeString() const;

    /**
     * @brief Retrieves all available parser names.
     *
     * @param callback Callback that receives each parser name.
     */
    static void getParserCompletions(const AutoCompleteCallback &callback);

    /**
     * @brief Checks whether a given file extension is supported.
     *
     * @param extension File extension to query (including the dot).
     * @return true if a parser supports the given extension.
     */
    [[nodiscard]] static bool isSupported(std::string_view extension);
};



#endif //HIGH_LIGHTER_H
