#ifndef HIGH_LIGHTER_H
#define HIGH_LIGHTER_H

#include <functional>
#include <optional>
#include <unordered_map>
#include <unordered_set>
#include <string_view>

#include <tree_sitter/api.h>

#include "../base/AutoCompleteCallback.h"
#include "../cursor/buffer/BufferEdit.h"
#include "../cursor/Cursor.h"
#include "HighLightId.h"
#include "TokenId.h"


/**
 * @brief Syntax highlighter using Tree-sitter for structured code parsing.
 *
 * Manages language-specific parsers, applies syntax highlighting, and supports
 * dynamic language switching based on file extensions or user commands.
 */
class HighLighter final {
private:
    /** @brief Represents a range of text with a specific TokenId. */
    struct Span final {
        const uint32_t start_column; ///< Starting column of the span.
        const uint32_t end_column;   ///< Ending column of the span.
        const TokenId token_id;      ///< Classification of the span.
        Span(const uint32_t startColumn, const uint32_t endColumn, const TokenId tokenId)
            : start_column(startColumn),
              end_column(endColumn),
              token_id(tokenId) {}
    };

private:
    /**
     * @brief Holds language-specific parser data, mapping logic, and queries.
     */
    struct Parser final {
        const TSLanguage* language;                         ///< Pointer to the Tree-sitter language definition.
        const std::string name;                             ///< Human-readable name of the language.
        const std::string argument_value;                   ///< Argument string usable in the prompt to select this parser.
        const std::unordered_set<std::string> files_format; ///< Set of supported file extensions for the language.
        const std::string query_source;                     ///< Source code of the Tree-sitter query for highlighting.
        TSQuery *query;                                     ///< Compiled Tree-sitter query.
    };

private:
    /** Reference to the cursor giving the text data to this highlighter */
    const Cursor &m_cursor;

    /** The current active parser module, or nullptr. Is used only to avoid a map lookup for each character.  */
    const Parser *p_current_parser;

    /** The Tree-sitter parser instance. */
    TSParser *p_ts_parser;

    /** The syntax tree generated by parsing. */
    TSTree *p_ts_tree;

    /** Tree-sitter query cursor. */
    TSQueryCursor *p_ts_query_cursor;

    /** Cache of highlighting spans per line. */
    mutable std::vector<std::vector<Span>> m_line_cache;

    /** Tree-sitter input wrapper for reading source text. */
    TSInput m_input;

    /** Currently active highlighting mode. */
    HighLightId m_high_light;

    /** true when a tree-sitter needs to reparse the tree and we to build a new cache */
    bool m_is_dirty;

private:
    /** @brief Tree-sitter input callback used to supply source code to the parser. */
    static const char *inputCallback(void *payload, uint32_t byteIndex, TSPoint position, uint32_t *bytesRead);

    /**
     * @brief Used by static inputCallback to read text from the cursor.
     *
     * @param line The line to start read.
     * @param column The column to start read.
     * @return A string view containing the line of text, starting from the said column, until the end of the said line (\n).
     */
    [[nodiscard]] std::optional<std::u16string_view> readCallback(uint32_t line, uint32_t column) const;

    /** Static map of registered parsers indexed by highlighting mode. */
    static const std::unordered_map<HighLightId, Parser> PARSERS;

public:
    /** @brief Deleted copy constructor. */
    HighLighter(const HighLighter &) = delete;

    /** @brief Deleted copy assignment operator. */
    HighLighter &operator=(const HighLighter &) = delete;

    /** @brief Free allocated resources. */
    ~HighLighter();

    /**
     * @brief Constructs the HighLighter with default values.
     *
     * @param cursor Reference to the source Cursor that feed data to this highlighter.
     */
    explicit HighLighter(Cursor &cursor);

    /**
     * @brief Sets the current syntax highlighting mode explicitly.
     *
     * @param highLight Highlight mode to activate.
     */
    void setMode(HighLightId highLight);

    /**
     * @brief Sets the highlighting mode based on file extension.
     *
     * This will fall back to no highlight if nothing matches.
     *
     * @param extension File extension (including the dot), e.g. ".cpp".
     */
    void setMode(std::string_view extension);

    /** @brief Parses or reparses the current input buffer. */
    void parse();

    /** @brief Updates the line cache using the current syntax tree and query. */
    void updateCache() const;

    /**
     * @brief Notifies the HighLighter about a range of text edits.
     *
     * @param edit Object describing the modified byte and position ranges. (provided by the Cursor class)
     */
    void edit(const BufferEdit &edit);

    /**
     * @brief Retrieves the TokenId (syntax classification) at a specific position.
     *
     * @param line Line number (zero-based).
     * @param column Column number (zero-based).
     * @return TokenId describing the syntax element at that position.
     */
    [[nodiscard]] TokenId getHighLightAtPosition(uint32_t line, uint32_t column) const;

    /** @return The current highlight mode name (e.g., "cpp", "json"). */
    [[nodiscard]] std::string_view getModeString() const;

    /**
     * @brief Retrieves all available parser names.
     *
     * @param callback Callback that receives each parser name.
     */
    static void getParserCompletions(const AutoCompleteCallback &callback);

    /**
     * @brief Checks whether a given file extension is supported.
     *
     * @param extension File extension to query (including the dot).
     * @return true if a parser supports the given extension.
     */
    [[nodiscard]] static bool isSupported(std::string_view extension);
};



#endif //HIGH_LIGHTER_H
